/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fish;

import fish.model.AsiaFishModel;
import fish.model.EuropeFishModel;
import fish.model.NorthAmericaFishModel;

public class App {
    public String getGreeting() {
        return "\n\nHello Fish!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        EuropeFishModel         europeFishModel = new EuropeFishModel();
        NorthAmericaFishModel   naFishModel = new NorthAmericaFishModel();
        AsiaFishModel           asiaFishModel = new AsiaFishModel();

        europeFishModel.solveAndPrintNumberOfSolutions();
        europeFishModel.solveAndPrintSolution();
        naFishModel.solveAndPrintNumberOfSolutions();
        naFishModel.solveAndPrintSolution();
        asiaFishModel.solveAndPrintNumberOfSolutions();
        asiaFishModel.solveAndPrintSolution();

        europeFishModel.solveXNumberOfTimes(1000);
        naFishModel.solveXNumberOfTimes(1000);
        asiaFishModel.solveXNumberOfTimes(1000);
    }
}
