/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.impl.AsiaFishModel;
import fish.model.impl.EuropeFishModel;
import fish.model.impl.NorthAmericaFishModel;

public class App {

    public static void main(String[] args) {
        EuropeFishModel europeFishModel = new EuropeFishModel();
        europeFishModel.solveAndPrintNumberOfSolutions();
        europeFishModel.addRandomConstraints(30);
        europeFishModel.solveAndPrintNumberOfSolutions();

        NorthAmericaFishModel naFishModel = new NorthAmericaFishModel(true, 0);
        naFishModel.solveAndPrintNumberOfSolutions();

        AsiaFishModel asiaFishModel = new AsiaFishModel(true, 15);
        asiaFishModel.solveAndPrintNumberOfSolutions();
    }
}
