/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.base.Region;
import fish.model.impl.AsiaFishModel;
import fish.merge.Checker;
import fish.merge.ModelMerger;

public class App2 {

    public static void main(String[] args) {
        AsiaFishModel asiaFishModel = new AsiaFishModel(true, 1);
        
        ModelMerger.contextualizeConstraints(asiaFishModel.getModel(), "region", Region.ASIA);
    }
}
