/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.base.Region;
import fish.model.impl.NorthAmericaFishModel;
import fish.merge.Checker;
import fish.merge.ModelMerger;

public class ContextualisationNA {

    public static void main(String[] args) {
        NorthAmericaFishModel model = new NorthAmericaFishModel(true, 0);
        model.solveAndPrintNumberOfSolutions();
        //ModelMerger.printAllConstraints(model);
        ModelMerger.contextualizeConstraints(model, "region", Region.NORTH_AMERICA);
        //ModelMerger.printAllConstraints(model);
        model.solveAndPrintNumberOfSolutions();
        Checker.checkConsistency(model);
        Checker.checkConsistencyByPropagation(model);
    }
}
