/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.base.Region;
import fish.model.impl.AsiaFishModel;
import fish.model.impl.EuropeFishModel;
import fish.model.impl.MergedModel;
import fish.merge.ModelMerger;

public class ContextualisationAndCombiningModels {

    public static void main(String[] args) throws Exception {
        int numberOfSolutions = 0;
        AsiaFishModel asiaFishModel = new AsiaFishModel(true, 0);
        numberOfSolutions = asiaFishModel.solveAndPrintNumberOfSolutions();
        ModelMerger.contextualizeConstraints(asiaFishModel, "region", Region.ASIA);
        numberOfSolutions = numberOfSolutions - asiaFishModel.solveAndPrintNumberOfSolutions();

        if(numberOfSolutions != 0) {
            throw new Exception("Contextualization of Asia failed");
        }

        EuropeFishModel europeFishModel = new EuropeFishModel(true, 0);
        numberOfSolutions = europeFishModel.solveAndPrintNumberOfSolutions();
        ModelMerger.contextualizeConstraints(europeFishModel, "region", Region.EUROPE);
        numberOfSolutions = numberOfSolutions - europeFishModel.solveAndPrintNumberOfSolutions();
        if(numberOfSolutions != 0) {
            throw new Exception("Contextualization of Europe failed");
        }
        
        MergedModel mergedModel = ModelMerger.mergeModels(asiaFishModel, europeFishModel, true);
        mergedModel.printAllVariables(true);
        mergedModel.printAllConstraints();

        //asiaFishModel.printAllConstraints();
        //europeFishModel.printAllConstraints();

        //asiaFishModel.printAllVariables(true);
        //europeFishModel.printAllVariables(true);
        
        int numberOfSolutionsAsia = asiaFishModel.solveAndPrintNumberOfSolutions();
        int numberOfSolutionsEu = europeFishModel.solveAndPrintNumberOfSolutions();
        numberOfSolutions = mergedModel.solveAndPrintNumberOfSolutions();
        numberOfSolutions = numberOfSolutions - numberOfSolutionsAsia - numberOfSolutionsEu;

        if(numberOfSolutions != 0) {
            throw new Exception("Merge failed");
        }
    }
}
