/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.base.Region;
import fish.model.impl.AsiaFishModel;

import fish.merge.ModelMerger;

public class Contextualisation {

    public static void main(String[] args) {
        AsiaFishModel asiaFishModel = new AsiaFishModel(true, 0);
        asiaFishModel.solveAndPrintNumberOfSolutions();
        AsiaFishModel contextAsiaModel = (AsiaFishModel) ModelMerger.contextualizeConstraints(asiaFishModel, "region", Region.ASIA);
        contextAsiaModel.solveAndPrintNumberOfSolutions();
    }
}
