/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package solve;

import fish.model.impl.AsiaFishModel;
import fish.model.impl.EuropeFishModel;
import fish.model.impl.MergedModel;
import fish.merge.Checker;
import fish.merge.ModelMerger;

public class Merge {

    public static void main(String[] args) {
        AsiaFishModel asiaFishModel = new AsiaFishModel(true, 0);
        asiaFishModel.solveAndPrintNumberOfSolutions();
        
        EuropeFishModel europeFishModel = new EuropeFishModel(true, 0);
        europeFishModel.solveAndPrintNumberOfSolutions();

        MergedModel m = ModelMerger.mergeModels(asiaFishModel, europeFishModel);
        Checker.checkConsistency(m);
        m.solveAndPrintNumberOfSolutions();

    }
}
